name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        uses: actions/setup-node@v2
      - run: npm install
        
      - name: Composer install
        uses: php-actions/composer@v5
        with:
          php_version: 7.4

      - name: Build
        uses: actions/setup-node@v2
      - run: npm run build
