name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        uses: actions/setup-node@v2
      - run: npm install
        
      - name: Composer install
        uses: ErickGomez98/composer@master
        with:
          action: 'install'
      
      - name: Build
        uses: actions/setup-node@v2
      - run: npm run build
