name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        uses: actions/setup-node@v2
      - run: npm install
        
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Composer install
        run: composer install
  
      - name: Build
        run: npm run build

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: KiepAppointments.zip
          path: easyappointments-0.0.0.zip
          
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./build/
          exclude: config-sample.php
            - config.php
