name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        uses: actions/setup-node@v2
      - run: npm install
        
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          extensions: gd2

      - name: Composer install
        run: composer install
  
      - name: Build
        run: npm run build
